services:
  workspace:
    container_name: ${PROJECT_NAME:-default}-workspace
    build:
      context: ./docker/workspace
    tty: true
    volumes:
      - ../:/workspace:cached
      - ~/.ssh:/root/.ssh:ro
    ports:
      - 5555:5555

