services:
  workspace:
    container_name: ${PROJECT_NAME:-default}-workspace
    build:
      context: ./docker/workspace
    tty: true
    volumes:
      - ../:/home/vscode/workspace:cached
      - ~/.ssh:/home/vscode/.ssh:ro
    ports:
      - 5555:5555

